### ISSUE TITLE
现在酷Q早就下架了，Centos如何使用你的框架部署机器人啊

### ISSUE THREAD

**Issue by a147022899** [Singularity0909/awesome-bot#2]
现在酷Q早就下架了，Centos如何使用你的框架部署机器人啊。你的框架似乎是QQ机器人架构的上层，之前是酷Q作为机器人的收发消息的，可是现在酷Q没有了，你给的go-cqhttp我不会部署啊。

**Comment by Singularity0909** [comment]
go-cqhttp 项目地址 https://github.com/Mrs4s/go-cqhttp/

你可以加我 QQ 联系，见主页

**Comment by Singularity0909** [comment]
> 现在酷Q早就下架了，Centos如何使用你的框架部署机器人啊。你的框架似乎是QQ机器人架构的上层，之前是酷Q作为机器人的收发消息的，可是现在酷Q没有了，你给的go-cqhttp我不会部署啊。

可以加我 QQ 联系，见主页
